# Generated by Django 6.1.1 on 2026-10-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('Department', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('HR', 'Human Resource')], max_length=3)),
                ('Designation', models.CharField(max_length=30)),
                ('Date_of_joining', models.DateField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=100)),
                ('Client_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=30)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Employees', models.ManyToManyField(related_name='projects', to='portal.employee')),
                ('Project_Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='portal.employee')),
            ],
        ),
    ]
